baseurl                  = "https://jordancrane.me"           # Your domain name
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Jordan Crane"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Mon Jan 02, 2006"
    dateformfull         = "Mon Jan 2 2006 15:04:05 EST"
    favicon              = "sam.ico"
    homepage             = "home"                           # What to call the home page link
    footerText           = "Personal site of Jordan Crane."

# Metadata for Open Graph and Twitter
    description          = "Personal site of Jordan Crane."               # Max 160 characters show in search results
    images               = ["tn.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Jordan Crane"
    # rss                = ""

[[params.mainMenu]]
    link = "posts"
    text = "logos"

[[params.mainMenu]]
    link = "resume.html"
    text = "ethos"

[[params.mainMenu]]
    link = "about"
    text = "pathos"

[imaging]
    quality = 75
